import {
  fadoAppProduct,
  nextBlog,
  ratracoProduct,
  QTVAppProduct,
  BHXAppProduct,
  UIKit,
} from "@/assets";
import { appConfig } from "./appConfig";

export const projects = [
  {
    title: "Quà tặng VIP",
    desc: "Quà tặng VIP is an application to accumulate points when customers buy product from thegioididong, Bách hóa XANH, Điện máy XANH",
    img: QTVAppProduct,
    authorLogo: appConfig.logoTGDD,
    projectName: "Quà tặng VIP",
    projectCategory: "Ecommerce App",
    time: "Sep - 2022",
    tagName: "Mobile",
    tagType: "mobile",
    links: {
      playStore: "",
      appleStore: "",
    },
    technology: ["React Native", "Javascript", "Typescript"],
    role: "Mobile Developer",
    roleDetail: [
      "Implemented, features create order (clean & care electrical equipment), voucher, cart, send feedback and complain,...",
      "Used GraphQL to app",
      "Focused on UX/UI optimization ",
    ],
    teamSize: 6,
    features: [
      "Easily search for products from many categories such as technology, beauty, health care, fashion, ... with full information about prices, colors, sizes, ...",
      "Update popular shopping trends, discounted products around the world",
      "Easily track order status through the app",
      "Tracking user for revenue optimization and push notifcation, voucher, gift with Insider & Google Analytics",
    ],
    image:
      "https://res.cloudinary.com/dxc0m9waq/image/upload/v1687700439/portfolio/Mobile_eeilxq.png",
  },
  {
    title: "Bách hóa XANH Online V2",
    desc: "Bách hóa XANH Online is an ecommerce project, specializes in selling everyday consumer products such as food, drink,...",
    img: BHXAppProduct,
    authorLogo: appConfig.logoTGDD,
    projectName: "Bách hóa XANH Online V2",
    projectCategory: "Ecommerce App",
    time: "June - 2022",
    tagName: "Mobile",
    tagType: "mobile",
    links: {
      playStore: "",
      appleStore: "",
    },
    technology: ["React Native", "Javascript"],
    role: "Mobile Developer",
    roleDetail: [
      "Implemented, maintained feature related to product listing display (category, search, product by brand...) ",
      "Improved UX/UI, app performance",
      "Knew about animation, implemented to app with React Native Aminated and 3rd library support",
    ],
    teamSize: 5,
    features: [
      "Easily search for products from many categories such as technology, beauty, health care, fashion, ... with full information about prices, colors, sizes, ...",
      "Update popular shopping trends, discounted products around the world",
      "Easily track order status through the app",
      "Tracking user for revenue optimization and push notifcation, voucher, gift with Insider & Google Analytics",
    ],
    image:
      "https://res.cloudinary.com/dxc0m9waq/image/upload/v1687701263/portfolio/RAM_12_512_GB_mqb2ww.png",
  },
  {
    title: "MWG SDK",
    desc: "MWG SDK likes UI Kit (include some common component such as Text, Button, Radio, Select...), for the purpose of providing components frequently used by mobile team projects",
    img: UIKit,
    authorLogo: appConfig.logoTGDD,
    projectName: "MWG SDK",
    projectCategory: "UI Components",
    time: "June - 2022",
    tagName: "Mobile",
    tagType: "mobile",
    links: {},
    technology: ["React Native", "Typescript"],
    role: "Mobile Developer",
    roleDetail: [],
    teamSize: 2,
    features: [],
    image:
      "https://res.cloudinary.com/dxc0m9waq/image/upload/v1687704501/portfolio/Copy_of_Copy_of_RAM_12_512_GB_khi5gh.png",
  },
  {
    title: "Fado Mobile App",
    desc: "Fado Mobile App is a product of Fado.vn on Android & IOS devices, users can use app for ordering products from Amazon easier.",
    img: fadoAppProduct,
    authorLogo: appConfig.logoFado,
    projectName: "Fado Mobile App",
    projectCategory: "Ecommerce App",
    time: "June - 2021",
    tagName: "Mobile",
    tagType: "mobile",
    links: {
      playStore:
        "https://play.google.com/store/apps/details?id=vn.fado.android",
      appleStore: "https://apps.apple.com/vn/app/id1190022173",
    },
    technology: ["React Native", "Expo", "Native Base", "Typescript"],
    role: "Frontend Developer",
    roleDetail: [
      "Owner listing product screens such as: Home, Search result, Campaign/event, Favorite...",
      "Research and implement tracking user with Firebase Analytics and Insider (third party partner)",
      "Implement Discount features",
      "Knowledge about Universal Links (Deeplink), multi-language with i18n, Mock Api, Redux Toolkit, Redux Persist",
    ],
    teamSize: 4,
    features: [
      "Easily search for products from many categories such as technology, beauty, health care, fashion, ... with full information about prices, colors, sizes, ...",
      "Update popular shopping trends, discounted products around the world",
      "Easily track order status through the app",
      "Tracking user for revenue optimization and push notifcation, voucher, gift with Insider & Google Analytics",
    ],
    image:
      "https://res.cloudinary.com/dxc0m9waq/image/upload/v1687702131/portfolio/Copy_of_RAM_12_512_GB_1_v6fd5e.png",
  },
  {
    title: "Ratraco Solution Webapp",
    desc: " Ratraco is a Railway Logistics Solution project, used for managing orders delivered by rail. The main users of the project are sales staff, accountants, shipping department",
    img: ratracoProduct,
    authorLogo: appConfig.logoFado,
    projectName: "Ratraco Solution",
    projectCategory: "Internal Accounting Webapp",
    time: "Jan - 2022",
    tagName: "Next JS",
    tagType: "web",
    links: {
      website: "https://staging-internal.woka.io/",
    },
    technology: ["NextJS", "Typescript", "Golang", "MUI v5"],
    role: "Frontend Developer",
    roleDetail: [
      "Created UI, base component (core), wrapped component,...",
      "Implemented feature customer management, feature statistics profit, revenue,...",
      "Validated form with React Hook Form & Yup schema",
      "Knew about server side rendering (SSR) & client side rendering (CLR)",
    ],
    teamSize: 5,
    features: [],
    image:
      "https://res.cloudinary.com/dxc0m9waq/image/upload/v1687704760/portfolio/Untitled_design_abwcpu.png",
  },
];
